name: Vulncheck SCA Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vulncheck-sca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Vulncheck SCA Workflow
        uses: LUCASRENAA/vulncheck-sca-workflow@main