name: Enviar requirements.txt e parâmetros para API Django

on:
  push:
    branches:
      - main  # Esse workflow é acionado a cada push na branch 'main'

jobs:
  send_requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v2
      
      - name: Instalar jq
        run: sudo apt-get install jq

      - name: Enviar requirements.txt e parâmetros para a API Django
        run: |
          curl -X POST "http:///127.0.0.1/api/scans/" \
          -H "Content-Type: multipart/form-data" \
          -F "file=@requirements.txt" \
          -F "technology=python" -o test.json

      # Passo 4: Verificar se "No vulnerabilities found" está no arquivo
      - name: Check if vulnerabilities found and upload report
        run: |
          if grep -q '"message": "No vulnerabilities found"' test.json; then
            echo "Nenhuma vulnerabilidade encontrada."
          else
            echo "Vulnerabilidades encontradas."
            vulnerabilities=$(cat test.json | jq -r '.vulnerabilities')

            echo "## Vulnerability Report" > vulnerabilities_report.md
            echo "| CVE | Severity | Package | Description | CVSS Score | Remediation |" >> vulnerabilities_report.md
            echo "| --- | -------- | ------- | ----------- | ---------- | ----------- |" >> vulnerabilities_report.md
            
            # Sort vulnerabilities by severity and generate table rows
            echo "$vulnerabilities" | jq -r 'sort_by(.cvss_nvd_score) | .[] | 
              "| \(.cve) | \(.severity) | \(.package_name) | \(.description) | \(.cvss_nvd_score) | [Remediation Link](\(.remediation)) |"' >> vulnerabilities_report.md

            cat vulnerabilities_report.md

            # Upload the vulnerabilities report as artifact in the same step
            uses: actions/upload-artifact@v4
            with:
              name: vulnerability-report
              path: vulnerabilities_report.md
            exit 1  # Marca como falha se houver vulnerabilidades
          fi
