name: Call External Workflow
on:
  push:
    branches: [ main ]

jobs:
  call-workflow:
    uses: LUCASRENAA/vulncheck-sca-workflow/.github/workflows/action.yml@teste-workflow-sca2
    # Se precisar passar secrets:
    # secrets:
    #   secret_name: ${{ secrets.SECRET_NAME }}