name: Call Reusable Workflow

on:
  push:
    branches:
      - '*'  # Será acionado em qualquer branch

jobs:
  trigger-reusable-workflow:
    uses: LUCASRENAA/vulncheck-sca-workflow/.github/workflows/action.yml@teste-workflow-sca2
    with:
      api_url: 'http://95.111.232.70/api/scans/'  # Pode ser alterado dinamicamente
      requirements_file: 'requirements.txt'     # Pode ser alterado dinamicamente
      technology: 'python'                      # Pode ser alterado dinamicamente
    runs-on: ubuntu-latest
