name: Run SCA Analysis

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  security-scan:
    uses: LUCASRENAA/vulncheck-sca-workflow/.github/workflows/reusable-sca-workflow.yml@main
    with:
      requirements_file: 'requirements.txt'
      technology: 'python'
      api_url: 'http://95.111.232.70/api/scans/'